import dotenv
import os
from llama_index.core import SimpleDirectoryReader
from llama_index.readers.web import BeautifulSoupWebReader
from llama_index.readers.file import PDFReader


from IPython.display import Markdown

dotenv.load_dotenv()

loader = BeautifulSoupWebReader()
parser = PDFReader()
url_dict = {
    "albany": ["https://www.albanyny.gov/FAQ.aspx?QID=126", 
    "https://www.albanynyrecycles.com/rescom-recycling", 
    "https://www.albanyny.gov/m/faq?cat=23&searchTerms=",
    "https://www.albanyny.gov/2359/Garbage-Collection",
    "https://www.albanyny.gov/2356/Mattress-Box-Spring-Disposal",
    "https://albanynyrecycles.com/hazardous-waste-electronics-/",
    "https://albanynyrecycles.com/paper-shredding/",
    "https://albanynyrecycles.com/yardwaste-collection/",
    "https://albanynyrecycles.com/compost-facility/",
    "https://albanynyrecycles.com/electronics-recycling/",
    "https://albanynyrecycles.com/participate/",
    "https://www.albanyny.gov/2360/Trash-Notices"],
    "allegany" : ["https://www.alleganyco.gov/departments/public-works/solid-waste-department",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/cardboard/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/clothing/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/electronics/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/glass/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/household-waste/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/metal-cans/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/paper/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/plastic/",
    "https://www.alleganyco.gov/departments/public-works/solid-waste-department/scrap-metal/"],
    "bronx": ["https://www.nyc.gov/site/dsny/collection/residents/recycling.page",
    "https://www.nyc.gov/site/dsny/collection/residents/trash.page",
    "https://www.nyc.gov/site/dsny/collection/residents/collection-laws-residents.page",
    "https://www.nyc.gov/site/dsny/collection/containerization/residential-containerization.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/appliances.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/automotive-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/batteries.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/clothing-household-fabrics-accessories.page", 
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/construction-debris.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/animals.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/electronics.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/furniture-mattresses.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/gas-cylinders-fire-extinguishers.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/harmful-household-products.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/ink-and-toner-cartridges.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/large-items.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/light-bulbs.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/medical-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mercury.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/metal-glass-plastic-cartons.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mixed-paper-cardboard.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/oil-grease.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/plant-yard-waste.page"],
    "broome":["https://broomecountyny.gov/solidwaste",
    "https://broomecountyny.gov/solidwaste/recycling",
    "https://broomecountyny.gov/solidwaste/recyclingbasics",
    "https://broomecountyny.gov/solidwaste/recycling-bins",
    "https://broomecountyny.gov/solidwaste/batteries",
    "https://broomecountyny.gov/solidwaste/business-recycling",
    "https://broomecountyny.gov/solidwaste/composting",
    "https://broomecountyny.gov/solidwaste/condebris-recycling",
    "https://broomecountyny.gov/solidwaste/christmas-tree-recycling",
    "https://broomecountyny.gov/solidwaste/landfill-drop-off",
    "https://broomecountyny.gov/solidwaste/multi-family-recycling",
    "https://broomecountyny.gov/solidwaste/plastic-bag-%26-plastic-film",
    "https://broomecountyny.gov/solidwaste/foamban",
    "https://broomecountyny.gov/solidwaste/recyclingfaq",
    "https://broomecountyny.gov/solidwaste/textile-recycling",
    "https://broomecountyny.gov/solidwaste/hazwaste",
    "https://broomecountyny.gov/solidwaste/hazwaste/commercialhhw",
    "https://broomecountyny.gov/solidwaste/hazwaste/faq",
    "https://broomecountyny.gov/solidwaste/hazwaste/paintrecycling",
    "https://broomecountyny.gov/solidwaste/electronics",
    "https://broomecountyny.gov/solidwaste/electronics/acceptedmaterials",
    "https://broomecountyny.gov/solidwaste/sharp-disposal-amp-unwanted-medications"],
    "cattaraugus":["https://www.cattco.gov/glassrecycling",
    "https://www.cattco.gov/tirerecycling",
    "https://www.cattco.gov/cardboardrecycling",
    "https://www.cattco.gov/2025refusechanges"],
    "cayuga":["https://www.cayugacounty.gov/699/Solid-Waste-Management-and-Recycling",
    "https://www.cayugacounty.gov/1872/Clothing-and-Textiles",
    "https://www.cayugacounty.gov/1870/Construction-Demolition-Debris",
    "https://www.cayugacounty.gov/706/Electronics",
    "https://www.cayugacounty.gov/1889/Ink-Cartridges",
    "https://www.cayugacounty.gov/708/Freon",
    "https://www.cayugacounty.gov/1876/Furniture-and-Large-Appliances",
    "https://www.cayugacounty.gov/705/Household-Hazardous-Waste",
    "https://www.cayugacounty.gov/709/Mercury",
    "https://www.cayugacounty.gov/1881/Food-Waste",
    "https://www.cayugacounty.gov/1882/Yard-Waste",
    "https://www.cayugacounty.gov/1914/NYS-PaintCare-Program",
    "https://www.cayugacounty.gov/1816/Medication-Disposal",
    "https://www.cayugacounty.gov/701/Sharps-Program",
    "https://www.cayugacounty.gov/1818/Electronics-Waste-Program",
    "https://www.cayugacounty.gov/1874/Paper-and-Cardboard",
    "https://www.cayugacounty.gov/1873/Plastics",
    "https://www.cayugacounty.gov/1869/Polystyrene-Foam-Styrofoam",
    "https://www.cayugacounty.gov/1009/Prescription-Drugs",
    "https://www.cayugacounty.gov/707/Propane-Tanks",
    "https://www.cayugacounty.gov/704/Tires"],
    "chautauqua" : ["https://chautauquacountyny.gov/landfill/landfill",
    "https://chautauquacountyny.gov/landfill/unacceptable-items",
    "https://chautauquacountyny.gov/landfill/recycling"],
    "chemung": ["https://www.chemungcountyny.gov/363/Solid-Waste-Management",
    "https://www.chemungcountyny.gov/641/Single-Stream-Recycling"],
    "chenango": ["https://www.chenangocountyny.gov/219/Waste-Management",
    "https://www.chenangocountyny.gov/334/Household-Hazardous-Waste",
    "https://www.chenangocountyny.gov/221/Solid-Waste-Facilities",
    "https://www.chenangocountyny.gov/283/Recycling-Operations",
    "https://www.chenangocountyny.gov/221/Solid-Waste-Facilities"],
    "clinton":["https://www.clintoncountyny.gov/index.php/landfill",
    "https://www.clintoncountyny.gov/landfill/drop-off-stations"],
    "columbia":["https://solidwaste.columbiacountyny.com/recycling-protocol/recycling-encyclopedia",
    "https://solidwaste.columbiacountyny.com"],
    "cortland":["https://www.cortlandcountyny.gov/280/Solid-Waste",
    "https://www.cortlandcountyny.gov/278/Recycling"],
    "delaware":["https://www.delcony.us/departments/sw/sw.htm", "https://www.delcony.us/departments/sw/recycling.htm", 
    "https://www.delcony.us/departments/sw/prohibitied.htm",
    "https://www.delcony.us/departments/sw/cleansweep.htm",
    "https://www.delcony.us/departments/sw/definitions.htm"],
    "dutchess": ["https://www.dutchessny.gov/Departments/Solid-Waste-Management/Solid-Waste-Management.htm",
    "https://www.dutchessny.gov/Departments/Solid-Waste-Management/Recycling-Solid-Waste-Management.htm",
    "https://www.dutchessny.gov/Departments/Solid-Waste-Management/Recycling-Encyclopedia.htm",
    "https://www.dutchessny.gov/Departments/Solid-Waste-Management/Helpsy.htm",
    "https://www.dutchessny.gov/Departments/Solid-Waste-Management/Household-Hazardous-Waste-Electronics-Event.htm"],
    "erie":["https://www.dutchessny.gov/Departments/Solid-Waste-Management/Household-Hazardous-Waste-Electronics-Event.htm",
    "https://www3.erie.gov/recycling/holiday-sustainability-tips",
    "https://www3.erie.gov/recycling/food-waste-management",
    "https://www3.erie.gov/recycling/household-hazardous-waste-hhw-collection-programs",
    "https://www.paintcare.org",
    "https://www3.erie.gov/recycling/materials-recycling-sites",
    "https://www3.erie.gov/recycling/electronics-recycling"],
    "essex":["https://essexcountyny.gov/community-resources"],
    "franklin":["https://www.franklincountyny.gov/departments/public_safety/soil_and_water/index.php"],
    "fulton":["https://www.fultoncountyny.gov/department-solid-waste",
    "https://www.fultoncountyny.gov/recycling",
    "https://www.fultoncountyny.gov/fulton-county-landfill",
    "https://www.fultoncountyny.gov/recycling",
    "https://www.fultoncountyny.gov/solid-waste-policy-guide"],
    "genesee":["https://www.geneseeny.gov/Department-Content/GLOW-Region-Solid-Waste",
    "https://www.geneseeny.gov/Department-Content/GLOW-Region-Solid-Waste/Household-Hazardous-Waste"],
    "greene":["https://greenecountyny.gov/departments/waste-transfer-stations/",
    "https://greenecountyny.gov/departments/waste-transfer-stations/accepted-waste/",
    "https://greenecountyny.gov/departments/waste-transfer-stations/disposing-of-lithium-batteries/",
    "https://greenecountyny.gov/departments/waste-transfer-stations/household-hazardous-waste/"],
    "hamilton":["https://www.hamiltoncountyny.gov/public-works"],
    "herkimer":["https://www.herkimercountyny.gov/departments/sewer-district"],
    "jefferson":["https://www.jeffersoncountyny.gov/departments/RecyclingWasteManagement", "https://www.jeffersoncountyny.gov/hours-locations"],
    "kings":["https://www.nyc.gov/site/dsny/collection/residents/recycling.page",
    "https://www.nyc.gov/site/dsny/collection/residents/trash.page",
    "https://www.nyc.gov/site/dsny/collection/residents/collection-laws-residents.page",
    "https://www.nyc.gov/site/dsny/collection/containerization/residential-containerization.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/appliances.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/automotive-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/batteries.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/clothing-household-fabrics-accessories.page", 
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/construction-debris.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/animals.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/electronics.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/furniture-mattresses.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/gas-cylinders-fire-extinguishers.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/harmful-household-products.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/ink-and-toner-cartridges.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/large-items.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/light-bulbs.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/medical-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mercury.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/metal-glass-plastic-cartons.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mixed-paper-cardboard.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/oil-grease.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/plant-yard-waste.page"],
    "lewis":["https://lewiscountyny.gov/departments/solid-waste/"],
    "madison":["https://www.madisoncounty.ny.gov/3013/Solid-Waste",
    "https://www.madisoncounty.ny.gov/2421/Recycling-Guides",
    "https://www.madisoncounty.ny.gov/2461/Frequently-Asked-Questions"],
    "monroe":["https://www.monroecounty.gov/ecopark",
    "https://www.monroecounty.gov/ecopark-appliances",
    "https://www.monroecounty.gov/ecopark-automotive",
    "https://www.monroecounty.gov/ecopark-batteries",
    "https://www.monroecounty.gov/ecopark-lithium",
    "https://www.monroecounty.gov/ecopark-bulky-plastic",
    "https://www.monroecounty.gov/ecopark-recycling",
    "https://www.monroecounty.gov/ecopark-danger",
    "https://www.monroecounty.gov/ecopark-donations",
    "https://www.monroecounty.gov/ecopark-electronics",
    "https://www.monroecounty.gov/ecopark-garbage",
    "https://www.monroecounty.gov/ecopark-light-bulbs",
    "https://www.monroecounty.gov/ecopark-misc",
    "https://www.monroecounty.gov/ecopark-paper-shredding",
    "https://www.monroecounty.gov/ecopark-pharmaceutical",
    "https://www.monroecounty.gov/ecopark-sharps",
    "https://www.monroecounty.gov/ecopark-covid-tests",
    "https://www.monroecounty.gov/ecopark-plastic-bags",
    "https://www.monroecounty.gov/ecopark-scrap-metal",
    "https://www.monroecounty.gov/ecopark-styrofoam",
    "https://www.monroecounty.gov/ecopark-electronics#ecig",
    "https://www.monroecounty.gov/ecopark-organic"],
    "montgomery":["https://www.montgomerycountyny.gov/web/sites/departments/solidwaste/default.asp",
    "https://www.co.montgomery.ny.us/web/sites/departments/solidwaste/acceptableitems.asp",
    "https://www.montgomerycountyny.gov/web/sites/departments/solidwaste/batteries.asp",
    "https://www.montgomerycountyny.gov/web/sites/departments/solidwaste/contact.asp",
    "https://www.montgomerycountyny.gov/web/sites/departments/solidwaste/electronics.asp",
    "https://www.montgomerycountyny.gov/web/sites/departments/solidwaste/hhw.asp",
    "https://www.montgomerycountyny.gov/web/sites/departments/solidwaste/trash.asp",
    "https://www.co.montgomery.ny.us/web/sites/departments/solidwaste/singlestreamrecycling.asp"
    ],
    "manhattan":["https://www.nyc.gov/site/dsny/collection/residents/recycling.page",
    "https://www.nyc.gov/site/dsny/collection/residents/trash.page",
    "https://www.nyc.gov/site/dsny/collection/residents/collection-laws-residents.page",
    "https://www.nyc.gov/site/dsny/collection/containerization/residential-containerization.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/appliances.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/automotive-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/batteries.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/clothing-household-fabrics-accessories.page", 
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/construction-debris.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/animals.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/electronics.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/furniture-mattresses.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/gas-cylinders-fire-extinguishers.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/harmful-household-products.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/ink-and-toner-cartridges.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/large-items.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/light-bulbs.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/medical-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mercury.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/metal-glass-plastic-cartons.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mixed-paper-cardboard.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/oil-grease.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/plant-yard-waste.page"],
    "niagara":["https://www.niagaracounty.gov/departments/m-r/refuse_disposal_district.php",
    "https://www.niagaracounty.gov/departments/m-r/public_works/index.php"],
    "oneida":["https://www.ohswa.org/resident/recycle/curbside-recycling/recycling-faq/",
    "https://www.ohswa.org/recycle/curbside-recycling/recycleone/",
    "https://www.ohswa.org/resident/recycle/curbside-recycling/acceptable-material/",
    "https://www.ohswa.org/resident/garbage/solid-waste-information/asbestos-disposal/",
    "https://www.ohswa.org/resident/household-hazardous-waste/hazardous-waste-information/household-hazardous-waste/",
    "https://www.ohswa.org/resident/household-hazardous-waste/hazardous-waste-information/house-hazardous-waste-faq/",
    "https://www.ohswa.org/recycle/special-programs/bulky-rigid-plastics/",
    "https://www.ohswa.org/recycle/special-programs/electronics-recycling/",
    "https://www.ohswa.org/recycle/special-programs/rechargeable-batteries/",
    "https://www.ohswa.org/garbage/city-of-utica-residents/city-of-utica-residents/#blue-anchor"],
    "onondaga":["https://ocrra.org/locations/",
    "https://ocrra.org/electronics/",
    "https://ocrra.org/waste/household-toxics/",
    "https://ocrra.org/how-do-i-get-rid-of/paint-and-paint-products/",
    "https://ocrra.org/how-do-i-get-rid-of/paper/",
    "https://ocrra.org/how-do-i-get-rid-of/plastic-bottles-jugs-jars/",
    "https://ocrra.org/how-do-i-get-rid-of/appliances/",
    "https://ocrra.org/how-do-i-get-rid-of/aerosol-cans-hazardous-contents/",
    "https://ocrra.org/how-do-i-get-rid-of/smoke-alarms/",
    "https://ocrra.org/how-do-i-get-rid-of/mattress/",
    "https://ocrra.org/how-do-i-get-rid-of/propane-tanks/",
    "https://ocrra.org/how-do-i-get-rid-of/construction-waste/"],
    "ontario":["https://ontariocountyrecycles.org",
    "https://ontariocountyrecycles.org/101/Residential-Recycling",
    "https://ontariocountyrecycles.org/153/Appliances",
    "https://ontariocountyrecycles.org/154/Batteries",
    "https://ontariocountyrecycles.org/178/Electronic-Waste",
    "https://ontariocountyrecycles.org/155/Furniture",
    "https://ontariocountyrecycles.org/156/Household-Hazardous-Waste",
    "https://ontariocountyrecycles.org/179/Junk-Mail",
    "https://ontariocountyrecycles.org/161/Light-Bulbs",
    "https://ontariocountyrecycles.org/157/Metal",
    "https://ontariocountyrecycles.org/158/Organics",
    "https://ontariocountyrecycles.org/164/NYS-Postconsumer-Paint-Collection-Progra",
    "https://ontariocountyrecycles.org/159/Plastic-Bags-Film",
    "https://ontariocountyrecycles.org/160/Textiles",
    "https://ontariocountyrecycles.org/162/Tires",
    "https://ontariocountyrecycles.org/163/Unused-Medicine",
    "https://ontariocountyrecycles.org/m/faq",
    "https://ontariocountyrecycles.org/173/Landfill"],
    "orange":["https://www.orangecountygov.com/434/Recycling",
    "https://www.orangecountygov.com/1561/Electronics-Recycling",
    "https://www.orangecountygov.com/1974/Scrap-Metal-Recycling",
    "https://www.orangecountygov.com/2083/Refrigerant-Recycling",
    "https://www.orangecountygov.com/2092/Battery-Recycling"],
    "orleans":["https://www.orleanscountyny.gov/community/orleans_county_refuse___recycling.php"],
    "oswego":["https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/new_page.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/index.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/trash_disposal.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/recycling.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/electronics_recycling.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/hhw.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/yard_waste_2.php",
    "https://www.oswegocountyny.gov/departments/infrastructure_facilities_and_technology/solid_waste/faq.php"],
    "otsego":["https://www.otsegocountyny.gov/departments/s-y/solid_waste/muncipal_drop_off_centers.php",
    "https://www.otsegocountyny.gov/departments/s-y/solid_waste/contact_information.php",
    "https://www.otsegocountyny.gov/departments/s-y/solid_waste/household_hazardous_waste_day.php",
    "https://www.otsegocountyny.gov/departments/solid_waste/how_do_i_get_rid_of_.php",
    "https://www.otsegocountyny.gov/departments/solid_waste/recycling_information.php",
    "https://www.otsegocountyny.gov/departments/solid_waste/index.php"],
    "putnam":["https://www.putnamcountyny.gov/health/recycle/"],
    "queens":["https://www.nyc.gov/site/dsny/collection/residents/recycling.page",
    "https://www.nyc.gov/site/dsny/collection/residents/trash.page",
    "https://www.nyc.gov/site/dsny/collection/residents/collection-laws-residents.page",
    "https://www.nyc.gov/site/dsny/collection/containerization/residential-containerization.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/appliances.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/automotive-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/batteries.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/clothing-household-fabrics-accessories.page", 
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/construction-debris.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/animals.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/electronics.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/furniture-mattresses.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/gas-cylinders-fire-extinguishers.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/harmful-household-products.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/ink-and-toner-cartridges.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/large-items.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/light-bulbs.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/medical-waste.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mercury.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/metal-glass-plastic-cartons.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/mixed-paper-cardboard.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/oil-grease.page",
    "https://www.nyc.gov/site/dsny/collection/get-rid-of/plant-yard-waste.page"],
    "rensselaer":["https://www.ercswma.org", "https://www.rensco.com/324/Sewer-District"],
    "rockland":["https://www.rocklandgreen.com/facilities/household-hazardous-waste-facility/",
    "https://www.rocklandcountyny.gov/departments/health/environmental-health/waste-management",
    "https://www.rocklandgreen.com/facilities/clarkstown-yard-waste-facility/",
    "https://www.rocklandgreen.com/special-programs/resident-events/sharps/",
    "https://www.rocklandgreen.com/special-programs/resident-events/medication-takeback/"],
    "saratoga": ["https://www.townofmaltany.gov/360/Recycle-in-Saratoga-County",
    "https://www.saratoga.com/green/saratoga-recycling-centers/"],
    "schenectady":["https://www.cityofschenectady.gov/222/Garbage-Recycling",
    "https://www.cityofschenectady.gov/535/Single-Stream-Recycling",
    "https://www.cityofschenectady.gov/531/Waste-Collection-Schedules"],
    "schoharie":["https://www.schohariecounty-ny.gov/departments/solid_waste___recycling/new_page.php",
    "https://www.schohariecounty-ny.gov/departments/solid_waste___recycling/index.php",
    "https://www.schohariecounty-ny.gov/departments/solid_waste___recycling/household_hazardous_waste_(hhw).php"],
    "schuyler":["https://www.schuylercounty.us/528/Recycling-Solid-Waste","https://www.schuylercounty.us/1174/Waste-Management"],
    "seneca":["https://www.senecacountyny.gov/gov/admin/recycling/", "https://senecacountycce.org/recycling", "https://www.senecacountyny.gov/gov/admin/recycling/guide/"],
    "stlawrence":["https://www.stlawco.gov/Departments/SolidWaste/Recycling",
    "https://www.stlawco.gov/Departments/SolidWaste",
    "https://www.stlawco.gov/Departments/SolidWaste/FAQ",
    "https://www.stlawco.gov/Departments/SolidWaste/HHW"],
    "steuben": ["https://www.steubencountyny.gov/330/Recycling", "https://www.steubencountyny.gov/323/Solid-Waste-Recycling",
    "https://www.steubencountyny.gov/324/E-Waste"],
    "suffolk":["https://www.suffolkcountyny.gov/Departments/Health-Services/Dump-Site-Information"],
    "sullivan":["https://www.sullivanny.gov/Departments/SolidWasteRecycling","https://www.sullivanny.gov/Departments/SolidWasteRecycling/CountyLandfill",
    "https://www.sullivanny.gov/Departments/SolidWasteRecycling/FAQ"],
    "tioga":["https://tiogacountyny.com/programs-agencies/sustainability-recycling/",
    "https://tiogacountyny.com/recycling-and-disposal-lookup-guide/"],
    "tompkins": ["https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Recycling-and-Composting/Curbside-Recycling",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Recycling-and-Composting/Additional-Recyclables-at-the-RSWC",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Recycling-and-Composting/Food-Scraps-Recycling",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Trash/Permits-and-Fees",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Trash/Trash-Tags",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Trash/Licensed-Haulers",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Trash/Illegal-Dumping",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/Household-Hazardous-Waste-HHW",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/Household-Hazardous-Waste-HHW/Non-Residential-HHW",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/ReBusiness-Partners-Program",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/Borrow-A-Bin",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/Preventing-Food-Waste-and-Redistributing-Surplus-Edible-Food",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/Buy-Green",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Other-Programs-and-Services/Reusable-Bag-Distribution",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Outreach/4Rs-in-Tompkins-County",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/About-Us/Financials",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/About-Us/Permits-Laws-and-Regulations",
    "https://www.tompkinscountyny.gov/All-Departments/Recycling-Materials-Management/Contact-Us"],
    "ulster":["https://ucrra.org/about-us/hours-and-locations/",
    "https://ucrra.org/waste-recycling/electronics/",
    "https://ucrra.org/waste-recycling/"],
    "warren": ["https://www.warrencountyny.gov/DPW/SolidWaste"],
    "washington":["https://www.washingtoncountyny.gov/281/Public-Works"],
    "wayne":["https://www.waynecountyny.gov/699/Waste-Reduction-Resources"],
    "westchester":["https://environment.westchestergov.com/facilities/h-mrf",
    "https://environment.westchestergov.com/residents/recycling-guidelines/electronics-monitors-tvs",
    "https://environment.westchestergov.com/residents/recycling-guidelines",
    "https://environment.westchestergov.com/residents/recycling-guidelines/plastic-bags",
    "https://environment.westchestergov.com/residents/household-recycling-days",
    "https://environment.westchestergov.com/residents/recycling-guidelines/mobile-shredder",
    "https://environment.westchestergov.com/residents/food-waste",
    "https://environment.westchestergov.com/residents/recycling-guidelines/other-household-items",
    ],
    "wyoming":["https://www.wm.com/us/en/location/ny/wyoming-county/trash-pickup-wyoming-county-ny"],
    "yates":["https://www.yatescountyny.gov/264/Recycling", "https://townofyates.org/refuse-recycling.php"]
    
}


# dictionary will store the counties. rag_pdf_data will have subfolders with county names, and then the pdf inside that.
for name, url_list in url_dict.items():
    # if the county has pdf data, load it. Only counties with actual pdf files should have a directory
    if (os.path.isdir('rag_pdf_data/'+name)):
        file_extractor = {".pdf": parser}
        pdf_documents = SimpleDirectoryReader(
            "./rag_pdf_data/"+name, file_extractor=file_extractor
        ).load_data()
        pdf_readmes = [(Markdown(f"{doc.text}")) for doc in pdf_documents]
  
        for i,readme_data in enumerate(pdf_readmes):        
            output_dir = "rag/rag_docs/" + name + "pdf" + str(i) +".md"
            header = f"""---
county: {name}
state: NY
content_type: pdf
source_file: {pdf_documents[i].metadata.get('file_path').split('rag_pdf_data')[1]}
---\n
            """
            try:
                with open(output_dir, "w", encoding="utf-8") as f:
                    f.write(header + readme_data.data)
                
            except Exception as e:
                print(f"An error occurred: {e}")
    

    documents = loader.load_data(url_list)

    readmes = [(Markdown(f"{doc.text}")) for doc in documents]

    
  
    for i,readme_data in enumerate(readmes):
        output_dir = "rag/rag_docs/" + name + str(i)+".md"
        header = f"""---
county: {name}
state: NY
content_type: html
source_url: {documents[i].metadata.get('URL')}
---\n
            """
        try:
            with open(output_dir, "w", encoding="utf-8") as f:
                f.write(header + readme_data.data)
            
        except Exception as e:
            print(f"An error occurred: {e}")